######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 19 18:47:11 2013
######################################################################
TEMPLATE = app
QT	+= widgets xml network websockets charts
#CONFIG	+= console
CONFIG	-= console

TARGET	= drm-module

QMAKE_CXXFLAGS	+= -std=c++17 
QMAKE_CFLAGS	+= -flto -ffast-math 
QMAKE_CXXFLAGS	+= -flto -ffast-math 
QMAKE_LFLAGS	+= -flto
#QMAKE_CFLAGS	+= -g
#QMAKE_CXXFLAGS	+= -g
#QMAKE_LFLAGS	+= -g
#QMAKE_CXXFLAGS	+= -fsanitize=address
#QMAKE_CFLAGS	+= -fsanitize=address
#QMAKE_LFLAGS	+= -fsanitize=address
RC_ICONS	=  drm.ico
RESOURCES       += resources.qrc

DEFINES         +=  __WITH_FDK_AAC__
#LIBS            += -lfdk-aac
#	LIBS            += -lfdk-aac-2
        PKGCONFIG       += fdk-aac
        INCLUDEPATH     += ./fdk-aac
INCLUDEPATH     += /usr/include/eigen3

DEPENDPATH += .  \
	      filters \
	      various \
	      input \
	      output \
	      displays \
	      data \
	      fac \
	      equalizer \
	      msc \
	      ofdm \
	      parameters \
	      sdc \
	      support 

INCLUDEPATH += .  \
	      filters \
	      various \
	      input \
	      output \
	      displays \
	      data \
	      fac \
	      equalizer \
	      msc \
	      ofdm \
	      parameters \
	      sdc \
	      support 

#CONFIG += static

# Input
HEADERS += ./constants.h \
	   ./radio.h \
	   ./super-frame.h \
	   ./basics.h \
	   ./output/audiosink.h \
	   ./input/socket-handler.h \
	   ./input/message-handler.h \
	   ./input/oscillator.h \
           ./various/ringbuffer.h \
           ./various/fft.h \
	   ./various/drm-converter.h \
	   ./various/program-list.h \
	   ./various/bandplan.h \
	   ./various/settings-handler.h \
	   ./filters/decimator.h \
	   ./filters/drm-bandfilter.h \
	   ./filters/lowpassfilter.h \
	   ./filters/rate-converter.h \
#	   ./filters/up-filter.h \
	   ./displays/clickable-chart.h \
	   ./displays/basic-scope.h \
	   ./displays/iq-display.h \
	   ./displays/eq-display.h \
	   ./data/data-processor.h \
	   ./data/message-processor.h \
	   ./data/aac-processor-fdk.h \
	   ./data/xheaac-processor.h  \
	   ./fac/fac-tables.h \
	   ./fac/fac-processor.h \
	   ./sdc/sdc-include.h \
	   ./sdc/sdc-processor.h \
	   ./sdc/sdc-streamer.h \
	   ./msc/backend-controller.h \
	   ./msc/msc-handler.h \
	   ./msc/msc-handler-qam16.h \
	   ./msc/msc-handler-qam64.h \
	   ./msc/msc-processor.h \
	   ./msc/msc-streamer.h \
	   ./ofdm/correlator.h \
	   ./ofdm/freqsyncer.h \
	   ./ofdm/reader.h \
	   ./ofdm/timesync.h \
	   ./ofdm/word-collector.h \
	   ./equalizer/equalizer-1.h \
	   ./equalizer/equalizer-base.h \
	   ./equalizer/estimator-2.h \
	   ./equalizer/matrix2.h \
	   ./equalizer/referenceframe.h \
	   ./parameters/msc-config.h \
	   ./parameters/puncture-tables.h \
	   ./parameters/state-descriptor.h \
	   ./support/checkcrc.h \
	   ./support/deinterleaver.h \
	   ./support/drm-shifter.h \
#	   ./support/fft-complex.h \
	   ./support/mapper.h \
	   ./support/mer16-values.h \
	   ./support/mer4-values.h \
	   ./support/mer64-values.h \
	   ./support/my-array.h \
	   ./support/prbs.h \
	   ./support/protlevels.h \
	   ./support/qam16-metrics.h \
	   ./support/qam4-metrics.h \
	   ./support/qam64-metrics.h \
	   ./support/viterbi-drm.h 

FORMS	+= ./drmdecoder.ui

SOURCES += ./main.cpp \
	   ./radio.cpp \
	   ./basics.cpp \
	   ./super-frame.cpp \
           ./output/audiosink.cpp \
	   ./input/socket-handler.cpp \
	   ./input/message-handler.cpp \
	   ./input/oscillator.cpp \
           ./various/fft.cpp \
           ./various/program-list.cpp \
           ./various/bandplan.cpp \
	   ./various/settings-handler.cpp \
	   ./various/drm-converter.cpp  \
	   ./filters/decimator.cpp \
	   ./filters/drm-bandfilter.cpp \
	   ./filters/lowpassfilter.cpp \
	   ./filters/rate-converter.cpp \
	   ./displays/clickable-chart.cpp \
	   ./displays/basic-scope.cpp \
	   ./displays/iq-display.cpp \
	   ./displays/eq-display.cpp \
	   ./data/data-processor.cpp \
	   ./data/message-processor.cpp \
	   ./data/aac-processor-fdk.cpp \
	   ./data/xheaac-processor.cpp \
	   ./data/up-filter.cpp \
	   ./fac/fac-tables.cpp \
	   ./fac/fac-processor.cpp \
	   ./sdc/sdc-processor.cpp \
	   ./sdc/sdc-streamer.cpp \
	   ./msc/backend-controller.cpp \
	   ./msc/msc-handler.cpp \
	   ./msc/msc-handler-qam16.cpp \
	   ./msc/msc-handler-qam64.cpp \
	   ./msc/msc-processor.cpp \
	   ./msc/msc-streamer.cpp \
	   ./ofdm/correlator.cpp \
	   ./ofdm/freqsyncer.cpp \
	   ./ofdm/reader.cpp \
	   ./ofdm/timesync.cpp \
	   ./ofdm/word-collector.cpp \
	   ./equalizer/equalizer-1.cpp \
	   ./equalizer/equalizer-base.cpp \
	   ./equalizer/estimator-2.cpp \
	   ./equalizer/matrix2.cpp \
	   ./equalizer/referenceframe.cpp \
	   ./parameters/msc-config.cpp \
	   ./parameters/puncture-tables.cpp \
	   ./parameters/state-descriptor.cpp \
	   ./support/checkcrc.cpp \
	   ./support/deinterleaver.cpp \
	   ./support/drm-shifter.cpp \
#	   ./support/fft-complex.cpp \
	   ./support/mapper.cpp \
	   ./support/mer16-values.cpp \
	   ./support/mer4-values.cpp \
	   ./support/mer64-values.cpp \
	   ./support/prbs.cpp \
	   ./support/protlevels.cpp \
	   ./support/qam16-metrics.cpp \
	   ./support/qam4-metrics.cpp \
	   ./support/qam64-metrics.cpp \
	   ./support/viterbi-drm.cpp

unix {
exists ("./.git") {
   GITHASHSTRING = $$system(git rev-parse --short HEAD)
   !isEmpty(GITHASHSTRING) {
       message("Current git hash = $$GITHASHSTRING")
       DEFINES += GITHASH=\\\"$$GITHASHSTRING\\\"
   }
}
isEmpty(GITHASHSTRING) {
    DEFINES += GITHASH=\\\"------\\\"
}

DEFINES		+= __WITH_FDK_AAC__
DESTDIR		= ./linux-bin

LIBS		+= -lfdk-aac
INCLUDEPATH	+= /usr/local/include/fdk-aac
LIBS		+= -L/usr/lib64
LIBS		+= -L/lib64
LIBS		+= -lrt -lsndfile -lsamplerate -lportaudio -lusb-1.0 -lfftw3f -ldl
#LIBS		+= -lqwt-qt5 -lrt -lsndfile -lsamplerate -lportaudio -lusb-1.0 -lfftw3f -ldl
}

win32 {
exists ("./.git") {
   GITHASHSTRING = $$system(git rev-parse --short HEAD)
   !isEmpty(GITHASHSTRING) {
       message("Current git hash = $$GITHASHSTRING")
       DEFINES += GITHASH=\\\"$$GITHASHSTRING\\\"
   }
}
isEmpty(GITHASHSTRING) {
    DEFINES += GITHASH=\\\"------\\\"
}

DESTDIR		= ./linux-bin
INCLUDEPATH	+= ./fdk-aac
INCLUDEPATH	+= ./fdk-aac
LIBS		+= -lfftw3f
LIBS            += -lfdk-aac-2
LIBS		+= -lportaudio
LIBS		+= -lusb-1.0
#LIBS		+= -lsndfile
LIBS		+= -lsamplerate
LIBS		+= -lole32
LIBS		+= -lwinmm
}

